/*

	setup.cl - Bryan Little 11/2025, montgomery arithmetic by Yves Gallot
	
	Generates starting factorial/primorial/compositorial using power and/or product tables.

	Intial compositorial is generated by calculating factorial divided by primorial using modular inverse.

	The CPU will run this kernel in many small chunks to limit kernel runtime.

	Setup and iterate kernels are the main compute intensive kernels.

*/

// left to right powmod montgomerizedbase^exp mod P, with 64 bit exponent
ulong powmodlg(ulong mbase, ulong exp, ulong p, ulong q) {
	ulong curBit = 0x8000000000000000;
	curBit >>= ( clz(exp) + 1 );
	ulong a = mbase;
	while( curBit )	{
		a = m_mul(a,a,p,q);
		if(exp & curBit){
			a = m_mul(a,mbase,p,q);
		}
		curBit >>= 1;
	}
	return a;
}

__kernel void primorial_setup(	__global ulong8 * g_prime,
				__global uint * g_primecount,
				__global ulong * g_smallprimeprod,
				const uint start,
				const uint end) {

	const uint gid = get_global_id(0);

	if(gid >= g_primecount[0]) return;

	// .s0=p, .s1=q, .s2=r2, .s3=one, .s4=two, .s5=nmo, .s6=residue of start# mod P
	ulong8 prime = g_prime[gid];

	if(!start){
		prime.s2 = add(prime.s4, prime.s4, prime.s0);
		prime.s2 = m_mul(prime.s2, prime.s2, prime.s0, prime.s1);
		prime.s2 = m_mul(prime.s2, prime.s2, prime.s0, prime.s1);
		prime.s2 = m_mul(prime.s2, prime.s2, prime.s0, prime.s1);
		prime.s2 = m_mul(prime.s2, prime.s2, prime.s0, prime.s1);
		prime.s2 = m_mul(prime.s2, prime.s2, prime.s0, prime.s1);		// 4^{2^5} = 2^64
		g_prime[gid].s2 = prime.s2;
	}

	for(uint i=start; i<end; ++i){
		ulong p = g_smallprimeprod[i];
		ulong montprimprod = m_mul(p, prime.s2, prime.s0, prime.s1);
		if(i){
			prime.s6 = m_mul(prime.s6, montprimprod, prime.s0, prime.s1);
		}
		else{
			prime.s6 = montprimprod;
		}
	}

	// done with initial primorial, store to global
	g_prime[gid].s6 = prime.s6;	// residue is equal to (startN-1)# mod P
}


__kernel void fc_setup(	__global ulong8 * g_prime,
			__global uint * g_primecount,
		 	__global ulong * g_smallprimeprod,
			const uint start,
			const uint end,
			__global uint2 * g_smallpowers,
			const uint startN,
			const uint done ) {

	const uint gid = get_global_id(0);

	if(gid >= g_primecount[0]) return;

	// .s0=p, .s1=q, .s2=r2, .s3=one, .s4=two, .s5=nmo, .s6=residue of startN!, .s7=startN in montgomery form
	ulong8 prime = g_prime[gid];
	uint i = start;

	// first iteration of kernel
	if(!start){
		++i;
		// setup r2 and montgomery form of startN
		// after r2 setup, .s4 is now used for primorial residue
		prime.s2 = add(prime.s4, prime.s4, prime.s0);
		prime.s2 = m_mul(prime.s2, prime.s2, prime.s0, prime.s1);
		prime.s2 = m_mul(prime.s2, prime.s2, prime.s0, prime.s1);
		prime.s2 = m_mul(prime.s2, prime.s2, prime.s0, prime.s1);
		prime.s2 = m_mul(prime.s2, prime.s2, prime.s0, prime.s1);
		prime.s2 = m_mul(prime.s2, prime.s2, prime.s0, prime.s1);	// 4^{2^5} = 2^64
		g_prime[gid].s2 = prime.s2;
		g_prime[gid].s7 = m_mul(startN, prime.s2, prime.s0, prime.s1);	// montgomerized startN
		// first iteration of factorial power table, base prime = 2
		// .s0=exp, .s1=curBit
		uint2 power = g_smallpowers[0];
		// left to right powmod
		ulong a = prime.s4;
		while( power.s1 ){
			a = m_mul(a, a, prime.s0, prime.s1);
			if(power.s0 & power.s1){
				a = add(a, a, prime.s0);		// base 2 we can add
			}
			power.s1 >>= 1;
		}
		prime.s6 = a;
		// first iteration of primorial, prime = 2
		// prime.s4 = prime.s4;
	}

	// remaining iterations of factorial and primorial, starting at prime = 3
	for(uint k=i; k<end; ++k){
		ulong sm_prime = g_smallprimeprod[k];
		// .s0=exp, .s1=curBit
		uint2 power = g_smallpowers[k];
		const ulong base = m_mul(sm_prime, prime.s2, prime.s0, prime.s1);
		ulong primepow;
		if(power.s0 == 1){
			primepow = base;
		}
		else{
			ulong a = base;
			while( power.s1 ){
				a = m_mul(a, a, prime.s0, prime.s1);
				if(power.s0 & power.s1){
					a = m_mul(a, base, prime.s0, prime.s1);
				}
				power.s1 >>= 1;
			}
			primepow = a;
		}
		prime.s6 = m_mul(prime.s6, primepow, prime.s0, prime.s1);
#ifdef COMP
		prime.s4 = m_mul(prime.s4, base, prime.s0, prime.s1);
	}
	
	if(done){
		ulong inv_primorial = powmodlg(prime.s4, prime.s0-2, prime.s0, prime.s1);
		// test if inverse exists
		ulong one = m_mul(inv_primorial, prime.s4, prime.s0, prime.s1);
		if(one != prime.s3){
			// inverse doesn't exist, must be a 2-PRP.  set to zero so next kernels can skip
			g_prime[gid].s0 = 0;
		}
		// .s4 = !/#
		prime.s4 = m_mul(prime.s6, inv_primorial, prime.s0, prime.s1);
	}

	// done with power/product tables, store to global
	g_prime[gid].s4 = prime.s4;	// residue is equal to (startN-1)!/((startN-1)#) mod P
#else
	}
#endif
	g_prime[gid].s6 = prime.s6;	// residue is equal to (startN-1)! mod P

}






